const router = require('express').Router()
const userRouter = require('../modules/user/user.router')
const authRouter = require('../modules/auth/auth.router')
const bannerRouter = require('../modules/banner/banner.router')
const brandRouter = require('../modules/brand/brand.router')
const categoryRouter = require('../modules/category/category.router')
const productRouter = require('../modules/product/product.router')
const cartRouter = require('../modules/cart/cart.router')
const shopRouter = require('../modules/shop/shop.router')

router.use('/user', userRouter)
router.use('/auth', authRouter)
router.use('/banner', bannerRouter)
router.use('/brand', brandRouter)
router.use('/category', categoryRouter)
router.use('/product', productRouter)
router.use('/order', cartRouter)
router.use('/shop', shopRouter)

module.exports = router